resolution: "720p"
aspect_ratio: "9:16"
num_frames: 48
fps: 24
frame_interval: 1

seed: 42
multi_resolution: "STDiT2"
dtype: "bf16"
condition_frame_length: 5
align: 5
num_sampling_steps: 30
cfg_scale: 7.0
aes: 6.5

prompt_as_path: true
prompt: [
"A vibrant underwater scene. A group of blue fish, with yellow fins, are swimming around a coral reef. The coral reef is a mix of brown and green, providing a natural habitat for the fish. The water is a deep blue, indicating a depth of around 30 feet. The fish are swimming in a circular pattern around the coral reef, indicating a sense of motion and activity. The overall scene is a beautiful representation of marine life."
]

# speedup
flash_attn: True
